noisy_search: fix calculation of confidence intervals
It was using the wrong variable. There was also the possibility of an
IndexError: mathematically it should be impossible, because csum[-1]
should be 1.0 (due to normalisation), but floating-point rounding is
full of evils.